#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.
insmod /home/orangepi/g_hid-demo/g_hid.ko idVendor=0x045e idProduct=0x00db bcdDevice=0x0109 iManufacturer='' iProduct='' iSerialNumber=0x00
#insmod /home/orangepi/g_hid-demo/g_hid.ko
echo connect > /sys/devices/platform/sunxi_usb_udc/udc/sunxi_usb_udc/soft_connect
echo PYTHONPATH="/home/orangepi/.local/lib/python3.5/site-packages/keyboard/"
export PYTHONPATH
python3 /home/orangepi/preprod/usbproxy.py > /tmp/log 2>&1
exit 0
